import DS from 'ember-data';

/**
 * Generated by `ember g adapter application`
 */
export default DS.RESTAdapter.extend({
  /**
   * Any part of the url after our server name
   * but before our model name
   */
  namespace: 'collections',

  /**
   * Sets the server that our data is on
   */
  host: 'http://tiny-lr.herokuapp.com',

  /**
   * Ember usually pluralizes urls for all models
   * Instead here we prepend everything with `rt-`
   * and we don't pluralize the model name
   */
  pathForType: function(modelName) {
    return `rt-${modelName}`;
  },
});
