import DS from 'ember-data';

/**
 * Generated by `ember g adapter application`
 */
export default DS.RESTAdapter.extend({
  namespace: 'collections',
  host: 'http://tiny-lr.herokuapp.com',

  pathForType: function(modelName) {
    return `rt-${modelName}`;
  },
});
